/**
 * datatype header automatically generated by cstar compiler
 * extracted from [[ghost::datatype]] attributes in reverse.c
 * intended for use by reverse_test.c
 */

#ifndef REVERSE_DATATYPE_H
#define REVERSE_DATATYPE_H

#include <stdbool.h>
#include <stdint.h>

/** datatype */
struct i32_list_block;
typedef struct i32_list_block *i32_list;

// users should only use the following functions to create and access List values
// all functions are appended a type name prefix to avoid name clashes

/** constructors */
i32_list nil();
i32_list cons(int32_t head, i32_list tail);

/** accessors */
int32_t head(i32_list l);
i32_list tail(i32_list l);

/** discriminators */
bool is_nil(i32_list l);
bool is_cons(i32_list l);

/** equality */
bool i32_list_eq(i32_list l1, i32_list l2);

/** debug only */
void i32_list_print(i32_list l);

#endif
