#!/usr/bin/env bash

CC=${CC:-cc}
export HOLLIGHT_DIR=${HOLLIGHT_DIR:-./hol-light}
export HOLLIGHT_USE_MODULE=${HOLLIGHT_USE_MODULE:-1}

if [ $# -ne 1 ]; then
    echo "Usage: $0 <input>"
    exit 1
fi

$CC $1 -L. -lhol_native -lm -o proof.exe
./proof.exe
