[workspace]
resolver = "2"
members = ["hol-rpc", "proof-kernel"]

[workspace.dependencies]
eyre = "0.6.12"
slotmap = { version = "1.0.7", features = ["serde"] }
ocaml-interop = "0.10.0"
ocaml-sys = "0.23.0"
serde = "1.0.197"
